<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Menu::insert([
            [
                'name' => 'Beranda',
                'link' => '/',
                'order' => 1,
                'is_parent' => false,
                'parent' => 0,
                'level' => 1,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Jurusan',
                'link' => '#',
                'order' => 2,
                'is_parent' => true,
                'parent' => 0,
                'level' => 1,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Profil',
                'link' => '/profil',
                'order' => 1,
                'is_parent' => false,
                'parent' => 2,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Sejarah',
                'link' => '/sejarah',
                'order' => 2,
                'is_parent' => false,
                'parent' => 2,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Visi, Misi dan Tujuan',
                'link' => '/visi-dan-misi',
                'order' => 3,
                'is_parent' => false,
                'parent' => 2,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Struktur Organisasi',
                'link' => '/struktur-organisasi',
                'order' => 4,
                'is_parent' => false,
                'parent' => 2,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Dosen dan Staff',
                'link' => '/staff',
                'order' => 5,
                'is_parent' => false,
                'parent' => 2,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Akademik',
                'link' => '#',
                'order' => 3,
                'is_parent' => true,
                'parent' => 0,
                'level' => 1,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Program Studi',
                'link' => '#',
                'order' => 1,
                'is_parent' => true,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'D4 Teknologi Rekayasa Perangkat Lunak',
                'link' => '/d4-trpl',
                'order' => 1,
                'is_parent' => false,
                'parent' => 9,
                'level' => 3,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'D4 Teknik Rekayasa Komputer',
                'link' => '/d4-trk',
                'order' => 2,
                'is_parent' => false,
                'parent' => 9,
                'level' => 3,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'D4 Bisnis Digital',
                'link' => '/d4-bisnis-digital',
                'order' => 3,
                'is_parent' => false,
                'parent' => 9,
                'level' => 3,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Kalender Akademik',
                'link' => '/kalender-akademik',
                'order' => 2,
                'is_parent' => false,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Pedoman Akademik',
                'link' => '/pedoman-akademik',
                'order' => 3,
                'is_parent' => false,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Peraturan Akademik',
                'link' => '/peraturan-akademik',
                'order' => 4,
                'is_parent' => false,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Jalur Masuk',
                'link' => '/jalur-masuk',
                'order' => 5,
                'is_parent' => false,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Beasiswa',
                'link' => '/beasiswa',
                'order' => 6,
                'is_parent' => false,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Biaya Pendidikan',
                'link' => '/biaya-pendidikan',
                'order' => 7,
                'is_parent' => false,
                'parent' => 8,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Kemahasiswaan',
                'link' => '#',
                'order' => 4,
                'is_parent' => true,
                'parent' => 0,
                'level' => 1,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Prestasi Mahasiswa',
                'link' => '/prestasi-mahasiswa',
                'order' => 1,
                'is_parent' => false,
                'parent' => 19,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Organisasi Kemahasiswaan',
                'link' => '/ormawa',
                'order' => 2,
                'is_parent' => false,
                'parent' => 19,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Kehidupan Kampus',
                'link' => '/kehidupan-kampus',
                'order' => 3,
                'is_parent' => false,
                'parent' => 19,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Alumni',
                'link' => 'https://jpc.poliwangi.ac.id/',
                'order' => 3,
                'is_parent' => false,
                'parent' => 19,
                'level' => 2,
                'link_target' => '_blank',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => true,
            ],
            [
                'name' => 'Dokumen',
                'link' => '/dokumen',
                'order' => 5,
                'is_parent' => false,
                'parent' => 0,
                'level' => 1,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
            [
                'name' => 'Kerjasama Industri',
                'link' => '/kerjasama-industri',
                'order' => 6,
                'is_parent' => false,
                'parent' => 2,
                'level' => 2,
                'link_target' => 'none',
                'is_footer' => false,
                'is_active' => true,
                'is_external_link' => false,
            ],
        ]);
    }
}
